mdp:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: media-data-platform
      dataset: mdp_staging
      location: europe-west1
      threads: 4
      timeout_seconds: 300
    ci:
      type: bigquery
      method: service-account
      project: media-data-platform
      dataset: mdp_staging
      location: europe-west1
      threads: 4
      timeout_seconds: 300
      keyfile: /dev/null
